//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationOrders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Number { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public bool Vip { get; set; }
    }
}
